"""initial regions

Revision ID: 58181bb7a229
Revises: 
Create Date: 2026-06-09 10:54:22.978529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58181bb7a229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_regions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('label_zh', sa.String(length=64), nullable=False),
    sa.Column('label_en', sa.String(length=64), nullable=False),
    sa.Column('region_type', sa.String(length=32), nullable=False),
    sa.Column('central_bank', sa.String(length=16), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_economic_memberships',
    sa.Column('country_iso', sa.CHAR(length=2), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['economic_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_iso', 'region_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_economic_memberships')
    op.drop_table('economic_regions')
    # ### end Alembic commands ###
