"""data pipeline tables

Revision ID: a520060dd1d5
Revises: 58181bb7a229
Create Date: 2026-06-09 11:19:25.811553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a520060dd1d5'
down_revision: Union[str, Sequence[str], None] = '58181bb7a229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('country_iso', sa.CHAR(length=2), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('binance_symbol', sa.String(length=32), nullable=True),
    sa.Column('akshare_func', sa.String(length=64), nullable=True),
    sa.Column('fred_series', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_class'), 'assets', ['asset_class'], unique=False)
    op.create_index(op.f('ix_assets_country_iso'), 'assets', ['country_iso'], unique=False)
    op.create_table('prices',
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'ts')
    )
    # Convert prices to a TimescaleDB hypertable partitioned on `ts`.
    op.execute("SELECT create_hypertable('prices', 'ts', if_not_exists => TRUE)")
    op.create_table('raw_news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_news_published_at'), 'raw_news', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_news_source'), 'raw_news', ['source'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_news_id', sa.BigInteger(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('classifier', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('origin_country', sa.String(length=2), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('affected_regions', sa.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_news_id'], ['raw_news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_occurred', 'events', ['occurred_at'], unique=False)
    op.create_index('idx_events_regions', 'events', ['affected_regions'], unique=False, postgresql_using='gin')
    op.create_table('impact_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('magnitude', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('timeframe_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impact_event', 'impact_predictions', ['event_id'], unique=False)
    op.create_table('impact_outcomes',
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('t0_price', sa.Numeric(), nullable=True),
    sa.Column('t1_price', sa.Numeric(), nullable=True),
    sa.Column('actual_pct', sa.Float(), nullable=True),
    sa.Column('actual_direction', sa.String(length=8), nullable=True),
    sa.Column('accuracy', sa.String(length=8), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['impact_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact_outcomes')
    op.drop_index('idx_impact_event', table_name='impact_predictions')
    op.drop_table('impact_predictions')
    op.drop_index('idx_events_regions', table_name='events', postgresql_using='gin')
    op.drop_index('idx_events_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_raw_news_source'), table_name='raw_news')
    op.drop_index(op.f('ix_raw_news_published_at'), table_name='raw_news')
    op.drop_table('raw_news')
    op.drop_table('prices')
    op.drop_index(op.f('ix_assets_country_iso'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_class'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
